# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, RETURN, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER ALT SHIFT, F, File manager (cwd), exec, uwsm-app -- nautilus --new-window "$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor

# Add extra bindings
bindd = CTRL ALT, J, Toggle J Workspace, togglespecialworkspace, j-workspace
bindd = CTRL ALT, K, Toggle K Workspace, togglespecialworkspace, k-workspace
bindd = CTRL ALT, L, Toggle L Workspace, togglespecialworkspace, l-workspace
bindd = CTRL ALT, S, Toggle S Workspace, togglespecialworkspace, s-workspace
# bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"
# bindd = SUPER SHIFT, R, exec, alacritty -e ssh your-server

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu

bindd = CTRL ALT, Q, Switch to workspace 1, workspace, 1
bindd = CTRL ALT, W, Switch to workspace 2, workspace, 2
bindd = CTRL ALT, E, Switch to workspace 3, workspace, 3
bindd = CTRL ALT, R, Switch to workspace 4, workspace, 4
bindd = CTRL ALT, T, Switch to workspace 5, workspace, 5
bindd = CTRL ALT, Y, Switch to workspace 6, workspace, 6
bindd = CTRL ALT, U, Switch to workspace 7, workspace, 7
bindd = CTRL ALT, I, Switch to workspace 8, workspace, 8
bindd = CTRL ALT, O, Switch to workspace 9, workspace, 9
bindd = CTRL ALT, P, Switch to workspace 10, workspace, 10

# Move active window to a workspace with SUPER + SHIFT + [1-9; 0]
bindd = CTRL SHIFT ALT, Q, Move window to workspace 1, movetoworkspace, 1
bindd = CTRL SHIFT ALT, W, Move window to workspace 2, movetoworkspace, 2
bindd = CTRL SHIFT ALT, E, Move window to workspace 3, movetoworkspace, 3
bindd = CTRL SHIFT ALT, R, Move window to workspace 4, movetoworkspace, 4
bindd = CTRL SHIFT ALT, T, Move window to workspace 5, movetoworkspace, 5
bindd = CTRL SHIFT ALT, Y, Move window to workspace 6, movetoworkspace, 6
bindd = CTRL SHIFT ALT, U, Move window to workspace 7, movetoworkspace, 7
bindd = CTRL SHIFT ALT, I, Move window to workspace 8, movetoworkspace, 8
bindd = CTRL SHIFT ALT, O, Move window to workspace 9, movetoworkspace, 9
bindd = CTRL SHIFT ALT, P, Move window to workspace 10, movetoworkspace, 10

