# Change the default Omarchy look'n'feel

# https://wiki.hyprland.org/Configuring/Variables/#general
general {
    # No gaps between windows or borders
    gaps_in = 0
    gaps_out = 0
    # border_size = 0

    # Use master layout instead of dwindle
    # layout = master
}

# https://wiki.hyprland.org/Configuring/Variables/#decoration
decoration {
    # Use round window corners
    # rounding = 8
}

# https://wiki.hypr.land/Configuring/Dwindle-Layout/
dwindle {
    # Avoid overly wide single-window layouts on wide screens
    # single_window_aspect_ratio = 1 1
    # no_gaps_when_only=true
}

# Disable borders when only one tile (window or group) exists
workspace = w[tv1], bordersize:0
# windowrulev2 = bordersize 0, onworkspace:w[tv1]

# Ensure floating windows still have a border
# windowrulev2 = bordersize 2, floating:1

# https://wiki.hypr.land/Configuring/Basics/Variables/#animations
animations {
    enabled = yes

    bezier = easeOutQuint,0.23,1,0.32,1

    animation = specialWorkspace, 1, 1, easeOutQuint, slidevert
}

windowrule = match:class chromium, opacity 0.95
windowrule = match:class chrome-www.youtube.com__-Default, opacity 0.9
